name = "my-wedding-site"
compatibility_date = "2024-04-28" # Use today's date or recent
pages_build_output_dir = "out"

[site]
bucket = "./out"  # If you're exporting your static site using `next export`
main = "functions/index.js"

# Functions configuration (Cloudflare Pages Functions)
[[functions]]
name = "api"
directory = "functions"

[[functions.routes]]
pattern = "/api/*"

[dev]
port = 4000